# Generated by Django 5.2 on 2025-05-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaña',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='¿Campaña activa?'),
        ),
    ]
