# Generated by Django 5.2 on 2025-05-06 07:25

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campaña_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('ha_votado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lista',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lista')),
                ('votante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.votante')),
            ],
        ),
    ]
