# Generated by Django 5.2 on 2025-05-07 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_votante_alter_lista_logo_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 7, 1, 26, 27, 832006)),
            preserve_default=False,
        ),
    ]
